# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 459cdcbc4ba9d02b6a33047d7a5869711f3121617bb364de061a713a97fd667daefc9fa709dad4d06bbbdd733a68e102da912c41fe3ef0112fbaa1a724f07b20

test:
  secret_key_base: 3998de2c4c519005b167ae872ae4d7e144ee35d30ac2cca41f40cb2a49a68da08fbd54e93b831512b02244451d60e6cb64b8b0d90d0acb4a4436604f5fd2c422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
